import Auth from './Auth'
import './globals.css'

export const metadata = {
  title: 'Main page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div>
          <Auth />
        </div>
        {children}
      </body>
    </html>
  )
}
